spring.application.name=InvAgent

spring.datasource.url=jdbc:mysql://localhost:3306/supply_db
spring.datasource.username=root
spring.datasource.password=Jujubeware123#

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true